export default [
  {
    i: 1,
    nameJP: 'アルベルト',
    nameKO: '알베르트',
    image: '1-albert_normal.png',
  },
  {
    uid: 2,
    nameJP: 'ブレンダ',
    nameKO: '브렌다',
    image: '2-brenda_normal.png',
  },
  {
    uid: 3,
    nameJP: 'クラーク',
    nameKO: '클라크',
    image: '3-klark_normal.png',
  },
  {
    uid: 4,
    nameJP: 'エミル',
    nameKO: '에밀',
    image: '4-emile_normal.png',
  },
  {
    uid: 5,
    nameJP: 'アクセル',
    nameKO: '엑셀',
    image: '5-axel_normal.png',
  },
  {
    uid: 6,
    nameJP: 'ルヴェン',
    nameKO: '루벤',
    image: '6-luven_normal.png',
  },
  {
    uid: 7,
    nameJP: 'サカタ',
    nameKO: '사카타',
    image: '7-sakata_normal.png',
  },
  {
    uid: 8,
    nameJP: 'アニタ',
    nameKO: '아니타',
    image: '8-anita_normal.png',
  },
  {
    uid: 9,
    nameJP: 'リチャード',
    nameKO: '리처드',
    image: '9-richard_normal.png',
  },
  {
    uid: 10,
    nameJP: 'アーク',
    nameKO: '아크',
    image: '10-ark_normal.png',
  },
  {
    uid: 11,
    nameJP: 'ジェノス',
    nameKO: '제노스',
    image: '11-genoce_normal.png',
  },
  {
    uid: 12,
    nameJP: 'ルーク',
    nameKO: '루크',
    image: '12-rook_normal.png',
  },
  {
    uid: 13,
    nameJP: 'ビショップ',
    nameKO: '비숍',
    image: '13-bishop_normal.png',
  },
  {
    uid: 14,
    nameJP: 'フェルダー',
    nameKO: '펠더',
    image: '14-felder_normal.png',
  },
  {
    uid: 15,
    nameJP: 'レロス',
    nameKO: '레로스',
    image: '15-leros_normal.png',
  },
  {
    uid: 16,
    nameJP: '大統領',
    nameKO: '대통령',
    image: '16-orwen_normal.png',
  },
  {
    uid: 17,
    nameJP: '',
    nameKO: '',
    image: '17-camilla_normal.png',
  },
  {
    uid: 18,
    nameJP: 'ランドルフ',
    nameKO: '랜돌프',
    image: '18-randolph_normal.png',
  },
  {
    uid: 22,
    image: '22-beegsoldiern.png',
  },
  {
    uid: 23,
    image: '23-beegsoldier.png',
  },
  {
    uid: 28,
    image: '28-arksoldier.png',
  },
];
