// game
export const REQUEST_GAME = 'REQUEST_GAME'
export const RECEIVE_GAME = 'RECEIVE_GAME'
export const FAILURE_GAME = 'FAILURE_GAME'

// characters
export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS'
export const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS'
export const FAILURE_CHARACTERS = 'FAILURE_CHARACTERS'

// parts
export const REQUEST_PARTS = 'REQUEST_PARTS'
export const RECEIVE_PARTS = 'RECEIVE_PARTS'
export const FAILURE_PARTS = 'FAILURE_PARTS'

// videos
export const REQUEST_VIDEOS = 'REQUEST_VIDEOS'
export const RECEIVE_VIDEOS = 'RECEIVE_VIDEOS'
export const FAILURE_VIDEOS = 'FAILURE_VIDEOS'
