// game
export const REQUEST_LIST__GAME = 'REQUEST_LIST__GAME'
export const RECEIVE_LIST__GAME = 'RECEIVE_LIST__GAME'
export const FAILURE_LIST__GAME = 'FAILURE_LIST__GAME'

// characters
export const REQUEST_LIST__CHARACTERS = 'REQUEST_LIST__CHARACTERS'
export const RECEIVE_LIST__CHARACTERS = 'RECEIVE_LIST__CHARACTERS'
export const FAILURE_LIST__CHARACTERS = 'FAILURE_LIST__CHARACTERS'

// parts
export const REQUEST_LIST__PARTS = 'REQUEST_LIST__PARTS'
export const RECEIVE_LIST__PARTS = 'RECEIVE_LIST__PARTS'
export const FAILURE_LIST__PARTS = 'FAILURE_LIST__PARTS'

// videos
export const REQUEST_LIST__VIDEOS = 'REQUEST_LIST__VIDEOS'
export const RECEIVE_LIST__VIDEOS = 'RECEIVE_LIST__VIDEOS'
export const FAILURE_LIST__VIDEOS = 'FAILURE_LIST__VIDEOS'
export const SELECT_INDEX__VIDEOS = 'SELECT_INDEX__VIDEOS'
